Doxygen MCP Server: server.DoxygenServer Class Reference
server.DoxygenServer Class Reference
Public Member Functions
__init__ (self)
setup_handlers (self)
Public Attributes
server = Server("doxygen-mcp")
dict projects = {}
Protected Member Functions
Sequence[TextContent] _create_project (self, Dict[str, Any] args)
Sequence[TextContent] _generate_documentation (self, Dict[str, Any] args)
Sequence[TextContent] _scan_project (self, Dict[str, Any] args)
Sequence[TextContent] _validate_documentation (self, Dict[str, Any] args)
Sequence[TextContent] _create_doxyfile (self, Dict[str, Any] args)
Sequence[TextContent] _check_doxygen_install (self, Dict[str, Any] args)
Sequence[TextContent] _suggest_file_patterns (self, Dict[str, Any] args)
Detailed Description
@brief Core Doxygen server implementation for Model Context Protocol
This class implements a comprehensive MCP server that provides full access to
Doxygen's documentation generation capabilities. It handles project initialization,
configuration management, documentation generation, and validation.
@details The server exposes Doxygen functionality through a clean MCP interface,
enabling AI assistants to generate and manage documentation for projects in
multiple programming languages. It supports advanced features like diagram
generation, coverage analysis, and multi-format output.
@note All tool methods are async to comply with MCP protocol requirements
Definition at line 199 of file server.py.
Constructor & Destructor Documentation
__init__()
server.DoxygenServer.__init__ (self)
Definition at line 215 of file server.py.
Member Function Documentation
_check_doxygen_install()
Sequence[TextContent] server.DoxygenServer._check_doxygen_install (self, Dict[str, Any] args) protected
Definition at line 554 of file server.py.
Referenced by setup_handlers().
_create_doxyfile()
Sequence[TextContent] server.DoxygenServer._create_doxyfile (self, Dict[str, Any] args) protected
Definition at line 551 of file server.py.
Referenced by setup_handlers().
_create_project()
Sequence[TextContent] server.DoxygenServer._create_project (self, Dict[str, Any] args) protected
@brief Create a new Doxygen project with intelligent configuration
@param args Dictionary containing project parameters
@return Sequence of TextContent with creation results
@details Creates a new Doxygen project by:
- Setting up the project directory structure
- Generating language-specific configuration
- Creating an optimized Doxyfile
- Storing project settings for future operations
@note The generated configuration includes language-specific optimizations
and file patterns appropriate for the specified programming language.
Definition at line 366 of file server.py.
References projects.
Referenced by setup_handlers().
_generate_documentation()
Sequence[TextContent] server.DoxygenServer._generate_documentation (self, Dict[str, Any] args) protected
Generate documentation using Doxygen
Definition at line 451 of file server.py.
Referenced by setup_handlers().
_scan_project()
Sequence[TextContent] server.DoxygenServer._scan_project (self, Dict[str, Any] args) protected
Scan project structure and identify files
Definition at line 511 of file server.py.
Referenced by setup_handlers().
_suggest_file_patterns()
Sequence[TextContent] server.DoxygenServer._suggest_file_patterns (self, Dict[str, Any] args) protected
@brief Suggest appropriate file patterns for a project
@param args Dictionary containing analysis parameters
@return Sequence of TextContent with pattern suggestions
@details Analyzes the project directory to identify file types and
suggests appropriate FILE_PATTERNS for Doxygen configuration based on
the actual files found in the project.
Definition at line 565 of file server.py.
Referenced by setup_handlers().
_validate_documentation()
Sequence[TextContent] server.DoxygenServer._validate_documentation (self, Dict[str, Any] args) protected
Definition at line 548 of file server.py.
Referenced by setup_handlers().
setup_handlers()
server.DoxygenServer.setup_handlers (self)
@brief Set up all MCP tool handlers
@details Registers all available tools with the MCP server framework,
including project management, documentation generation, validation,
and utility functions. Each tool is properly configured with input
schemas and documentation.
Definition at line 220 of file server.py.
References _check_doxygen_install(), _create_doxyfile(), _create_project(), _generate_documentation(), _scan_project(), _suggest_file_patterns(), and _validate_documentation().
Member Data Documentation
projects
dict server.DoxygenServer.projects = {}
Definition at line 217 of file server.py.
Referenced by _create_project().
server
server.DoxygenServer.server = Server("doxygen-mcp")
Definition at line 216 of file server.py.
Referenced by test_server.TestDoxygenServer.test_check_doxygen_install_not_found(), test_server.TestDoxygenServer.test_check_doxygen_install_success(), test_server.TestDoxygenServer.test_create_project_invalid_path(), test_server.TestDoxygenServer.test_create_project_success(), test_server.TestDoxygenServer.test_generate_documentation_no_doxyfile(), test_server.TestDoxygenServer.test_generate_documentation_success(), test_server.TestDoxygenServer.test_list_tools(), test_server.TestDoxygenServer.test_scan_project_nonexistent(), and test_server.TestDoxygenServer.test_scan_project_success().
The documentation for this class was generated from the following file:
server.py